name: CI
on: [push]
jobs:
  # Lighthouse CI - Disabled during active development for faster CI and simplified setup
  # Re-enable before production launch for performance testing
  # lhci:
  #   name: Lighthouse
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
  #     - name: Lighthouse
  #       uses: shopify/lighthouse-ci-action@v1
  #       with:
  #         store: ${{ secrets.SHOP_STORE_OS2 }}
  #         password: ${{ secrets.SHOP_PASSWORD_OS2 }}
  #         access_token: ${{ secrets.SHOP_ACCESS_TOKEN }}
  #         collection_handle: all
  #         lhci_github_app_token: ${{ secrets.LHCI_GITHUB_TOKEN }}
  #         pull_theme: ${{ secrets.SHOP_PULL_THEME }}
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Theme Check
        uses: shopify/theme-check-action@v2
        with:
          token: ${{ github.token }}
